project:
  type: website
  output-dir: docs

website:
  title: "HKI Courses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index-qgt.qmd
      - index-bios-25328.qmd
      - index-logistics.qmd
  body-footer: |
      © [HakyImLab 2024](https://hakyimlab.org) - [MIT License](https://opensource.org/licenses/MIT)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



