project:
  type: website

website:
  title: "HakyimLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index-bios-25328.qmd
      - index-logistics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



